"""have_recorded (inside gui._ensure_local_frames) must require every recorded
frame to actually be present on disk, not just frame 00000.jpg.

Before background prefetch existed (and before --anchor-only could narrow a
chain's view directory down to just its anchor +/- context frames, including
for a chain the current session never opened directly, the prefetched next
chain), a view directory either existed complete or didn't exist at all: prep
only ever ran synchronously, to completion, on the GUI thread. Now two new,
routine ways exist for a directory to hold 00000.jpg while NOT holding every
recorded frame:

  - a daemon prefetch thread (gui.ReviewGUI._prefetch_next) gets killed (window
    closed) mid-build, leaving a partial view directory behind.
  - an --anchor-only session narrows a chain's view down to anchor +/- context
    frames only; if that SAME chain is later opened in a FULL (non-anchor-only)
    session, the old 00000.jpg-only check would see the recorded, full-chain
    frame_to_z (e.g. 88 entries) and trust the directory to serve it, even
    though only the narrow set is physically on disk.

See docs/superpowers/specs/2026-10-01-next-chain-frame-prefetch-design.md.

Torch-free, GPU-free:
    py -3 -m pytest tests/test_ensure_local_frames_partial.py
"""
from __future__ import annotations

import pathlib
import sys
import types

sys.path.insert(0, str(pathlib.Path(__file__).resolve().parent.parent))

import gui


def test_a_directory_missing_its_last_recorded_frame_is_regenerated(monkeypatch, tmp_path):
    """Simulates the real failure: state.json records an 88-frame frame_to_z (a
    full chain, generated by a prior full session or propagation run), but the
    view directory on disk only actually has frame 0 -- e.g. left behind by a
    killed prefetch, or by an earlier --anchor-only session for this same
    chain. Opening it in a full (non-anchor_only) session must regenerate, not
    silently trust the recorded frame_to_z against a directory that cannot
    actually serve all of it."""
    frames_dir = tmp_path / "chain_views" / "AIAL_chain00_s8"
    frames_dir.mkdir(parents=True)
    (frames_dir / "00000.jpg").write_bytes(b"fake-jpeg")   # only frame 0 is really there

    recorded_frame_to_z = {i: 1000 + i for i in range(88)}   # the full chain's mapping

    prepared = {}

    def _prepare(chain, annotate_df, *, scale, frames_root, anchor_catmaid_z,
                neuron, chain_idx, z_range=None):
        prepared["called"] = True
        prepared["z_range"] = z_range
        return str(tmp_path / "fresh"), recorded_frame_to_z, 0, 88

    monkeypatch.setattr(gui.pipeline, "prepare_video_frames", _prepare)

    frames_dir_out, frame_to_z, anchor_idx = gui._ensure_local_frames(
        str(frames_dir), recorded_frame_to_z, 0, chain={}, cw=None,
        cfg=types.SimpleNamespace(scale=8, frames_root=tmp_path),
        annotate_df=None, anchor_catmaid_z=1000, neuron="AIAL", chain_idx=0,
        anchor_only=False, chain_dir=tmp_path)

    assert prepared["called"] is True, (
        "a directory with only frame 0 of an 88-frame recorded chain must be "
        "treated as incomplete and regenerated, not trusted as fully recorded")
    assert frames_dir_out == str(tmp_path / "fresh")
    # a full (non-anchor_only) regeneration must not be narrowed to just the anchor
    assert prepared["z_range"] is None


def test_a_fully_populated_directory_is_still_reused_without_regenerating(monkeypatch, tmp_path):
    """The flip side, so the fix doesn't just make everything regenerate: when
    every recorded frame (index 0 and the last index) is actually on disk, the
    recorded frames_dir is reused as before, with no call into
    prepare_video_frames at all."""
    frames_dir = tmp_path / "chain_views" / "AIAL_chain00_s8"
    frames_dir.mkdir(parents=True)
    recorded_frame_to_z = {0: 1000, 1: 1001, 2: 1002}
    for i in range(3):
        (frames_dir / f"{i:05d}.jpg").write_bytes(b"fake-jpeg")

    def _prepare(*a, **k):
        raise AssertionError("must not regenerate when every recorded frame is present")

    monkeypatch.setattr(gui.pipeline, "prepare_video_frames", _prepare)

    frames_dir_out, frame_to_z, anchor_idx = gui._ensure_local_frames(
        str(frames_dir), recorded_frame_to_z, 1, chain={}, cw=None,
        cfg=types.SimpleNamespace(scale=8, frames_root=tmp_path),
        annotate_df=None, anchor_catmaid_z=1001, neuron="AIAL", chain_idx=0,
        anchor_only=False, chain_dir=tmp_path)

    assert frames_dir_out == str(frames_dir)
    assert frame_to_z == recorded_frame_to_z
    assert anchor_idx == 1


def test_an_empty_recorded_frame_to_z_is_never_trusted_as_recorded(monkeypatch, tmp_path):
    """Edge case the fix must not mishandle: an empty recorded frame_to_z (nothing
    to actually compare against) must not be treated as "have_recorded", even if
    00000.jpg happens to exist on disk for some unrelated reason."""
    frames_dir = tmp_path / "chain_views" / "AIAL_chain00_s8"
    frames_dir.mkdir(parents=True)
    (frames_dir / "00000.jpg").write_bytes(b"fake-jpeg")

    prepared = {}

    def _prepare(chain, annotate_df, *, scale, frames_root, anchor_catmaid_z,
                neuron, chain_idx, z_range=None):
        prepared["called"] = True
        return str(tmp_path / "fresh"), {0: 1000}, 0, 1

    monkeypatch.setattr(gui.pipeline, "prepare_video_frames", _prepare)

    gui._ensure_local_frames(
        str(frames_dir), {}, None, chain={}, cw=None,
        cfg=types.SimpleNamespace(scale=8, frames_root=tmp_path),
        annotate_df=None, anchor_catmaid_z=1000, neuron="AIAL", chain_idx=0,
        anchor_only=False, chain_dir=tmp_path)

    assert prepared["called"] is True


if __name__ == "__main__":
    import pytest
    sys.exit(pytest.main([__file__, "-v"]))
