"""Extract the per-slide presenter notes into one readable talk script.

The notes live in HTML comments inside each slide file, which means they are only
visible in Slidev's presenter mode, one slide at a time. That is fine while
presenting and useless for rehearsing. This walks the deck in presentation order
and emits `script.md`: every slide's title, what is on screen, and the notes
verbatim, with a timing budget that adds up.

Generated, so do not hand-edit `script.md`. Edit the notes in the slide files and
re-run this.

Run: py -3 make_script.py        (from the presentation/ directory)
Out: script.md
"""
from __future__ import annotations

import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
MASTER = HERE / "slides.md"
OUT = HERE / "script.md"

NOTES_RE = re.compile(r"<!--\s*\n?PRESENTER NOTES:\s*(.*?)-->", re.S)
SRC_RE = re.compile(r"^src:\s*(.+?)\s*$", re.M)
TIMING_RE = re.compile(r"^Timing:\s*(.+?)\s*$", re.M)


def slide_files() -> list[tuple[int, Path]]:
    """Slide 1 is the master file itself; the rest come from its `src:` order."""
    text = MASTER.read_text(encoding="utf-8")
    out = [(1, MASTER)]
    for i, rel in enumerate(SRC_RE.findall(text), start=2):
        out.append((i, (HERE / rel).resolve()))
    return out


def strip_frontmatter(text: str) -> str:
    if not text.startswith("---"):
        return text
    end = text.find("\n---", 3)
    return text[end + 4:] if end != -1 else text


def title_of(text: str, path: Path) -> str:
    for line in strip_frontmatter(text).splitlines():
        if line.startswith("# "):
            return line[2:].strip()
    return path.stem


def _clean(item: str) -> str:
    item = re.sub(r"<[^>]+>", "", item)
    item = re.sub(r"\*\*(.+?)\*\*", r"\1", item)
    item = re.sub(r"\*(.+?)\*", r"\1", item)
    return item.replace("<br>", " ").strip()


def on_screen(text: str) -> list[str]:
    """What the audience actually sees.

    Most slides use markdown bullets. A few (the four asks, the thanks slide) build
    their content out of HTML divs instead, and a bullets-only reader would report
    those slides as blank, so fall back to the visible text of the body.
    """
    body = strip_frontmatter(NOTES_RE.sub("", text))
    body = re.sub(r"<style>.*?</style>", "", body, flags=re.S)

    bullets = [_clean(ln.strip()[2:]) for ln in body.splitlines()
               if ln.strip().startswith("- ")]
    bullets = [b for b in bullets if b]
    if bullets:
        return bullets

    # No bullets: recover the visible prose, skipping headings, markup-only lines,
    # image tags and table rules.
    out = []
    for line in body.splitlines():
        s = line.strip()
        if not s or s.startswith(("#", "<!--", "|---", "<img")):
            continue
        cleaned = _clean(s)
        if cleaned and not cleaned.startswith("|"):
            out.append(cleaned)
        elif cleaned.startswith("|"):
            cells = [c.strip() for c in cleaned.strip("|").split("|") if c.strip()]
            if cells:
                out.append(" / ".join(cells))
    return out


def notes_of(text: str) -> str:
    m = NOTES_RE.search(text)
    return m.group(1).strip() if m else ""


def timing_seconds(notes: str) -> tuple[int, int] | None:
    """(low, high) seconds. None for 'on demand', which is not in the running budget."""
    m = TIMING_RE.search(notes)
    if not m:
        return None
    raw = m.group(1).lower()
    if "on demand" in raw:
        return None
    nums = [float(n) for n in re.findall(r"\d+(?:\.\d+)?", raw)]
    if not nums:
        return None
    unit = 60 if "minute" in raw else 1
    lo, hi = nums[0], nums[-1]
    return int(lo * unit), int(hi * unit)


def fmt(seconds: int) -> str:
    m, s = divmod(seconds, 60)
    return f"{m} min {s:02d} s" if m else f"{s} s"


def main() -> None:
    rows = []
    for num, path in slide_files():
        if not path.exists():
            rows.append((num, path, f"[MISSING FILE: {path.name}]", [], "", None))
            continue
        text = path.read_text(encoding="utf-8")
        notes = notes_of(text)
        rows.append((num, path, title_of(text, path), on_screen(text), notes,
                     timing_seconds(notes)))

    main_rows = [r for r in rows if r[5] is not None]
    lo = sum(r[5][0] for r in main_rows)
    hi = sum(r[5][1] for r in main_rows)
    backup = [r for r in rows if r[5] is None]

    L: list[str] = []
    L.append("# Talk script: C. elegans nerve-ring segmentation")
    L.append("")
    L.append("Generated from the presenter notes in the slide files by `make_script.py`.")
    L.append("Do not edit this file directly; edit the notes in `slides/` and re-run the script.")
    L.append("")
    L.append(f"- Slides in the running order: {len(rows)} "
             f"({len(main_rows)} timed, {len(backup)} on demand)")
    L.append(f"- Timed budget: **{fmt(lo)}** to **{fmt(hi)}**")
    L.append("- Quoted lines are meant to be said close to verbatim. Bullets under "
             "\"key points\" are beats, not a script; say them in your own words.")
    L.append("")
    L.append("## Running order and timings")
    L.append("")
    L.append("| # | Slide | Timing |")
    L.append("|---|---|---|")
    running = 0
    for num, _p, title, _b, _n, t in rows:
        if t is None:
            L.append(f"| {num} | {title} | on demand |")
            continue
        running += t[1]
        window = fmt(t[0]) if t[0] == t[1] else f"{fmt(t[0])} to {fmt(t[1])}"
        L.append(f"| {num} | {title} | {window} (by {fmt(running)}) |")
    L.append("")
    L.append("---")
    L.append("")

    for num, path, title, bullets, notes, t in rows:
        tag = " (backup)" if t is None else ""
        L.append(f"## Slide {num}{tag}. {title}")
        L.append("")
        if t is not None:
            window = fmt(t[0]) if t[0] == t[1] else f"{fmt(t[0])} to {fmt(t[1])}"
            L.append(f"*Target: {window}. Source: `{path.name}`*")
        else:
            L.append(f"*On demand, for questions. Source: `{path.name}`*")
        L.append("")
        if bullets:
            L.append("**On screen:** " + " · ".join(bullets))
            L.append("")
        if notes:
            L.append(re.sub(r"^Timing:.*$", "", notes, flags=re.M).strip())
        else:
            L.append("*(no notes)*")
        L.append("")
        L.append("---")
        L.append("")

    OUT.write_text("\n".join(L) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(HERE)}  "
          f"({len(rows)} slides, timed budget {fmt(lo)} to {fmt(hi)})")


if __name__ == "__main__":
    main()
